### ISSUE TITLE
Integrate Falco for run time threat detection

### ISSUE THREAD

**Issue by srodenhuis** [redkubes/otomi-core#1001]
Threat detection is one of the last missing pieces in Otomi to cover all required security capabilities.

# User story
As an admin, I want to be able to turn on Falco for threat detection, so I can monitor all deployed workloads for unusual behavior

## Use cases
1. An admin can turn on Falco. When enabled:
- Falco will send notifications to alert manager (if enabled)
- Falco exporter is configured to send all events to Prometheus
- A Falco dashboard is enabled in Grafana
- Falco Macros are pre-configured for Otomi related rule deviations (removing the noise)
- Marcos can be customized by the admin using rawValues

## Definition Of Ready
- [ ] The story use cases are clear and described in Gherkin
- [ ] Requirements and use cases have been reviewed (in our daily session -- the developers rotate -- everyone is responsible!)
- [x] The story is self-contained and has no dependencies on other stories
- [ ] The story has been estimated in complexity points
- [ ] Atomic SMART tasks have been created that reflect the functional requirements
- [ ] Atomic SMART tasks reflect any dependencies on other tasks in this story (affecting order of delivery)
- [ ] The story is reviewed and approved by @srodenhuis or @morriz

## Tasks
core:
1. [x] add Falco charts and values
2. [x] add Falco Grafana dashboards

api:
1. [x] add Falco app schema

console:
1. [x] add Falco app icon

## Definition Of Done

- [x] [Tasks](##Tasks) are done.
- [ ] Unit Tests are added with the code (if relevant and practical)
- [ ] Functional Tests are written down (if relevant and practical)
- [ ] Functional Tests are performed by another developer/ tester(if relevant and practical)
- [ ] (Architecture) Design Record(s) have been added as `adr/*.md` and appended to list in `adr/_index.md`.
- [x] Schema and demo files have been updated to reflect code changes (if relevant).
- [ ] Documentation has been updated (if relevant).
- [ ] Functionality, code, and/or documentation have been peer reviewed.
