### ISSUE TITLE
As a team member I would like to open terminal with kubectl access

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#1121]
# User story
As a team member I would like to open terminal with kubectl access, so I can monitor state of k8s resource and perform some basic maintenance actions

## Use cases
1. A user can open ttyd in we browser and use kubectl with a service account associated with this particular user

## Definition Of Ready

- [ ] The story use cases are clear and described in Gherkin
- [ ] Requirements and use cases have been reviewed (in our daily session -- the developers rotate -- everyone is responsible!)
- [ ] The story is self-contained and has no dependencies on other stories
- [ ] The story has been estimated in complexity points
- [ ] Atomic SMART tasks have been created that reflect the functional requirements
- [ ] Atomic SMART tasks reflect any dependencies on other tasks in this story (affecting order of delivery)
- [ ] The story is reviewed and approved by @srodenhuis or @morriz

## Tasks

core:
1. [x] define ingress for ttyd services  (core.yaml)
1. [x] Create Docker file for the custom ttyd image
2. [x] Create pipeline for building and using image to otomi Dockerhub
3. [ ] User authz - cross check content go JWT with accessed URL 
4. [ ] set correct namespace in generated kubeconfig (configmap) 

api:
1. [x] implement endpoint to create ttyd Pod
2. [x] call k8s api to create  ttyd Pod in a team-admin namespace
3. [x] call k8s api to create service account for a user in a team-admin namespace
4. [x] call k8s api to create role to access in a team namespace
5. [x] call k8s api to create role binding  in a team namespace
6. [x] do not allow users to read service account tokens
7. [ ] create `RoleBindings` based on groups membership  

console:
1. [x] add button to create/join ttyd console
2. [x] add button to close ttyd console
3. [x] add button to delete ttyd pods
4. [x] add button to open ttyd console in a new browser tab
5. [x] add button to minimize/maximize ttyd console
6. [x] add handle bar to resize ttyd console and resizing functionality

## Definition Of Done

- [ ] [Tasks](##Tasks) are done.
- [ ] Unit Tests are added with the code (if relevant and practical)
- [ ] Functional Tests are written down (if relevant and practical)
- [ ] Functional Tests are performed by another developer/ tester(if relevant and practical)
- [ ] (Architecture) Design Record(s) have been added as `adr/*.md` and appended to list in `adr/_index.md`.
- [ ] Schema and demo files have been updated to reflect code changes (if relevant).
- [ ] Documentation has been updated (if relevant).
- [ ] Functionality, code, and/or documentation have been peer reviewed.

**Comment by Ani1357** [comment]
Currently working on [cloudshell branch](https://github.com/redkubes/otomi-core/tree/ani/feat/cloudshell) of otomi-core. The branch contains the core.yaml file changes where we added entry for the tty.<fqdn> endpoint and also a folder containing the starting point manifests for tty. The folder contains a small readme on how to deploy it.

In order to make the setup work I need to:
1 - add a new entry in the hosts section for the `team-dev` (testing team) gateway resource to math the url in the Virtual service (ex. `tty.192.168.64.101.nip.io`)
2 - I have to delete the automatically created VirtualService in the team-admin since it conflicts with the new VS created in the team-dev

**Comment by Ani1357** [comment]
After talk with Jeho we concluded that the igress resource is not needed since it otomi creates one (after adding it to the core.yaml) and also to hardcode the value of the gateway in the virtualservice resource. Also updated the naming of the resources.

Issue: the tty endpoint created by otomi contains this hosts configuration:
![image.png](https://images.zenhubusercontent.com/642ac5c36fe3e326cc94305b/be576f0e-3df1-4370-97a2-ec7378a2f1ee)
The string before the slash indicates the allowed namespaces from which a VirtualService can use the gateway. Check https://istio.io/latest/docs/reference/config/networking/gateway/
This means we either modify the gateway hosts field or **why not deploy the tty pod in the admin namespace** ?? 🤨 @j-zimnowoda 
The user does not need to see the pod and/or modify it.

ToDo:
- Integrate the role and config map at the team-ns chart
- Improve the image creation

**Comment by Ani1357** [comment]
Reworked again the tty manifests file:
- now we will use a pod instead of a deployment for tty
- added the team as part of the pod name in case a user tries to create tty sessions for different teams(otherwise it would conflict because of the name)

Important: at the moment we are extending the otomi-api serviceaccount roles in order for it to be able to create the related resources. This is something we should discuss if it is acceptable or not

**Comment by Ani1357** [comment]
Extending the otomi-api roles was not enough since as part of the tty creation we need to deploy also a rolebinding resource. The rolebinding is expected to bind the tty pod service account with a role that has access to all resources and verbs of the namespace its going to interact with( so * resources and * verbs).
[To prevent privilege escalation](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#privilege-escalation-prevention-and-bootstrapping) the K8s RBAC model works as follows:

To allow a user to create/update roles:
- Grant them a role that allows them to create/update Role or ClusterRole objects, as desired.
- Grant them permission to include specific permissions in the roles they create/update:
implicitly, by giving them those permissions (if they attempt to create or modify a Role or ClusterRole with permissions they themselves have not been granted, the API request will be forbidden)
or explicitly allow specifying any permission in a Role or ClusterRole by giving them permission to perform the escalate verb on roles or clusterroles resources in the rbac.authorization.k8s.io API group

**Comment by Ani1357** [comment]
- Created the following [pipeline](https://github.com/redkubes/otomi-core/blob/ani/feat/cloudshell/.github/workflows/cloudtty-build-push.yml) for building, pushing and versioning the cloudtty image.
- Need access to set the correct dockerhub token in the github actions secrets @j-zimnowoda

**Comment by Ani1357** [comment]
Created final pipeline and pushed the initial tty image to otomi's dockerhub repository: https://hub.docker.com/r/otomi/tty

After its merged to main:
- if we need to bump the MAJOR version we need to pass the  "[TTY][MAJOR]" string in the commit message
- if we need to bump the MINOR version we need to pass the  "[TTY][MINOR]" string in the commit message
- if none of this conditions are met will check if the "tools/Dockerfile-tty" file was changed. If yes will bump the patch version

**Comment by j-zimnowoda** [comment]
We will create two enhancements:
1) user authn with istio
2) proper handling JWT groups that are not reflected in k8s cluster
