### ISSUE TITLE
Leverage ArgoCD to deploy Teams

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#1298]
# WHY

To improve platform robustness, reliability, time to deploy and self healing.

# User Story

**AS A** a platform engineer
**I WANT TO** all Helm releases to be independently deployed
**SO** I can benefit from the [controller pattern](https://kubernetes.io/docs/concepts/architecture/controller/#controller-pattern)

# Acceptance criteria

**GIVEN** all Helm releases defined in the `helmfile.d/`
**WHEN** Tekton pipeline is triggered
**THEN** it deploys all Helm releases as ArgoCD Applications

**GIVEN** installed Helm releases  in existing instance of Otomi
**WHEN** Otomi upgrade happens
**THEN** ArgoCD application can takeover control over the already  installed Helm releases 

**Design document:** https://redkubes.atlassian.net/wiki/spaces/KB/pages/5283217409/GitOps+-+deployment+pipeline
**Spike:** https://app.zenhub.com/workspaces/dev-5e7e84dddc966f05a627a19b/issues/gh/redkubes/unassigned-issues/576

# TASKS
- [x] dedicated Tekton pipeline for teams
- [x] generate argocd applications for each helm release 
- [x] add otomi apply-as-apps command 
- [ ] add `otomi` Project to Argocd
- [x] modify pipeline to deploy Application (otomi apply-as-apps)
- [x] handle deployment with nip.io
- [ ] allow to set full branch name at otomi.version (e.g.: jeho/feat/argocd), so ArgoCD applications can refer to a branch from otomi-core repo in Gtihub (nice to have)
- [ ] show status of ArgoCD Team application to the user (nice to have)
- [ ] strip values provided to the team chart

# TESTS
- [x] install with no teams 
- [x] install with teams 
- [x] adding a team should trigger both pipelines
- [ ] adding a service should only trigger the otomi-task-teams pipeline => fails, both pipelines are triggered
- [ ] removing a team => fails (Otomi removes the whole team config , thus otomi does not know what that it was removed.)
- [x] adding service to the team 
- [x] modifying platform apps but not team should trigger only platform pipeline
- [x] modifying platform apps and team should trigger both team and platform pipelines
- [x] enabling team monitoring stack
- [x] disabling team monitoring stack
- [x] long run test
- [ ] otomi upgrade from 2.1.0 (both pipelines should be triggered

# Definition of done

- [ ] Relevant PRs are merged
- [ ] Tested by peer
- [ ] Updated documentation reviewed by peer
- [ ] Short demo video recorded and stored on google drive (if applicable)

**Comment by j-zimnowoda** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DEV-5e7e84dddc966f05a627a19b/issues/redkubes/otomi-core/1298?planning-poker) with Zenhub @Ani1357 @dennisvankekem @ElderMatt @ferruhcihan @staticvoid255

**Comment by j-zimnowoda** [comment]
1. How to instruct Argo to manage existing helm release and corresponding resources?

**Comment by j-zimnowoda** [comment]
Made some progress and implemented generation of the Applicaiton manifests.

**Comment by j-zimnowoda** [comment]
Today I manage to deploy existing helm releases as argocd applications!

```
# k get application -A
NAMESPACE   NAME                                        SYNC STATUS   HEALTH STATUS
argocd      argocd-argocd-operator                      Synced        Healthy
argocd      argocd-argocd-operator-artifacts            Synced        Healthy
argocd      argocd-argocd-operator-cr                   Synced        Healthy
argocd      cert-manager-cert-manager                   Synced        Healthy
argocd      cert-manager-cert-manager-artifacts         Synced        Healthy
argocd      cnpg-system-cloudnative-pg                  Synced        Healthy
argocd      default-knative-operator                    OutOfSync     Healthy
argocd      drone-drone                                 Synced        Healthy
argocd      gitea-gitea                                 Synced        Healthy
argocd      gitea-gitea-artifacts                       Synced        Healthy
argocd      harbor-harbor                               Synced        Healthy
argocd      harbor-harbor-artifacts                     OutOfSync     Healthy
argocd      harbor-harbor-otomi-db                      Synced        Healthy
argocd      ingress-ingress-nginx-artifacts             Synced        Healthy
argocd      ingress-ingress-nginx-platform              Synced        Healthy
argocd      istio-operator-istio-operator               Synced        Healthy
argocd      istio-operator-istio-operator-artifacts     Synced        Healthy
argocd      istio-system-istio-artifacts                Synced        Healthy
argocd      istio-system-oauth2-proxy                   Synced        Healthy
argocd      istio-system-oauth2-proxy-artifacts         Synced        Healthy
argocd      keycloak-keycloak-artifacts                 Synced        Healthy
argocd      keycloak-keycloak-operator                  Synced        Healthy
argocd      keycloak-keycloak-operator-cr               Synced        Healthy
argocd      keycloak-keycloak-otomi-db                  Synced        Healthy
argocd      knative-serving-knative-serving             Synced        Healthy
argocd      knative-serving-knative-serving-artifacts   Synced        Healthy
argocd      maintenance-job-copy-certs                  Synced        Healthy
argocd      maintenance-job-copy-certs-argocd           Synced        Healthy
argocd      maintenance-job-gitea-prepare               Synced        Healthy
argocd      maintenance-job-harbor                      Synced        Healthy
argocd      maintenance-job-keycloak                    Synced        Healthy
argocd      maintenance-wait-for-otomi-realm            Synced        Healthy
argocd      olm-operator-lifecycle-manager              Synced        Healthy
argocd      otomi-otomi-api                             Synced        Healthy
argocd      otomi-otomi-console                         Synced        Healthy
argocd      team-admin                                  Synced        Healthy
argocd      team-admin-nodejs-helloworld                Unknown       Healthy
argocd      team-admin-team-ns-admin                    Synced        Healthy
argocd      team-demo                                   Synced        Healthy
argocd      team-demo-httpbin                           Synced        Healthy
argocd      team-demo-nginx-deployment                  Synced        Healthy
argocd      team-demo-nginx-ksvc                        Synced        Healthy
argocd      team-demo-nodejs-helloworld                 Unknown       Healthy
argocd      team-demo-team-ns-demo                      Synced        Healthy
argocd      team-demo-tekton-dashboard-demo             Synced        Healthy
argocd      tekton-pipelines-tekton-dashboard           Synced        Healthy
argocd      tekton-pipelines-tekton-pipelines           Synced        Healthy
argocd      tekton-pipelines-tekton-triggers            Synced        Healthy
```

**Comment by staticvoid255** [comment]
seriously cool

**Comment by j-zimnowoda** [comment]
# TEST CASE 1
```
cd
VALUES_DIR=/tmp/values-apps
rm -rf $VALUES_DIR
mkdir $VALUES_DIR
VALUES_REPO=$(k get configmap -n otomi otomi-api -o json | jq -r .data.GIT_REPO_URL)
export GIT_SSL_NO_VERIFY=true; 
git clone "https://$VALUES_REPO" $VALUES_DIR
cd "$VALUES_DIR"
kubectl get -n drone secret drone-envfile -ojson | jq -r '.data.env' | base64 -d | sed "s/: /=/" > .secrets
otomi apply-as-apps
kubectl -n argocd get application
```

**Comment by j-zimnowoda** [comment]
I tested the upgrade to the version that is leveraging ArgoCD application. It was successful and smooth.
However, I need to modify the job to install Otomi from scratch to install OLM and ArgoCD.
Moreover, I need to check if Otomi-tasks are performed as expected.

**Comment by j-zimnowoda** [comment]
I still need to ensure that pipeline for teams creates team namespace if a new team is created.
Then I will leverage ArgoCD to deploy teams. The code is ready and needs to cherrypicked from another branch.

**Comment by j-zimnowoda** [comment]
On team creation also job-keycloak needs to be executed.

**Comment by j-zimnowoda** [comment]
Teams pipeline should run always
Platform pipeline should run if platform config change or `teams.yaml` change.

**Comment by j-zimnowoda** [comment]
If there is not team then pipeline fails with the following error:
```
2023-12-21T13:54:10.229Z otomi:global:error Error: err: no releases found that matches specified selector() and environment(default), in any helmfile
    at hfCore (/home/app/stack/dist/src/common/hf.js:44:30)
    exit code: 3
    at ChildProcess.<anonymous> (/home/app/stack/node_modules/zx/dist/bundle.cjs:15261:22)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
```

**Comment by j-zimnowoda** [comment]
https://github.com/redkubes/otomi-core/pull/1413
