### ISSUE TITLE
Implement conftest

### ISSUE THREAD

**Issue by rawc0der** [redkubes/otomi-core#153]
# Tasks
stack:
- [x] Add conftest static binary to the tooling docker image
- [x] extract policies to `policies/*.rego`
- [x] Add `bin/validate-policies.sh` script to validate scripts against all policies
- [x] Update Otomi CLI to use `otomi validate-policies`
- [ ] Provide documentation and examples
