### ISSUE TITLE
As a user I want obtain access to a kubernetes cluster by authenticating with custom IdP (draft)

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#207]
# User story
As a user I want obtain access to a kubernetes cluster by authenticating with custom IdP, so I can reuse identities and associated policies defined by my organisation.

We want to provide seamless and consistent user experience to all teams that are onboarded in otomi container platform.
The user authentication for all otomi core services is already implemented. It is time to implement OIDC authentication flow for users that wants to access the cluster by using kubectl.

# Tasks
core:
- [ ] integrate jwt-to-rbac app
- [ ] expose jwt-to-rbac app as private service
- [ ] configure keycloak to support device code authentication flow for `otomi kubectl-config` command
- [ ] add `otomi kubectl-config` command that will interact with authentication app and create kubeconfig

References: 
https://banzaicloud.com/blog/k8s-rbac/
https://github.com/banzaicloud/jwt-to-rbac
https://kubernetes.io/docs/reference/access-authn-authz/authentication/#openid-connect-tokens

# Definition Of Done
- [ ] Tasks are done
- [ ] (Unit) Tests are performed
- [ ] (Architecture) Design Record(s) have been added as `adr/*.md` and appended to list in `adr/_index.md`
- [ ] Specs and demo files have been updated to reflect code changes
- [ ] Documentation has been updated
- [ ] Functionality, code, and/or documentation has been peer reviewed
- [ ] Relevant team members have been notified

**Comment by j-zimnowoda** [comment]
On Wednesday I moved forward with running PoC
- configured keycloak claims and extended JWT TTL
- created few issues in their project 
https://github.com/banzaicloud/jwt-to-rbac/issues/42,  
https://github.com/banzaicloud/jwt-to-rbac/issues/41
https://github.com/banzaicloud/jwt-to-rbac/issues/39
- create one PR to jwt-to-rbac 
https://github.com/banzaicloud/jwt-to-rbac/pull/40
The community responded today. It is a good sign that the project has responsive community.
- configure jwt-to-rbac in otomi
- successfully converted ID token into SA token!

**Comment by Morriz** [comment]
@j-zimnowoda very nice. Can you pull in the references to our private docs repo? Otherwise people can't access them. Maybe also add this as a "discussion".  We can use that space to iterate on design/architecture, so that we also keep a trail of our reasoning (issues are gone when closed).

**Comment by j-zimnowoda** [comment]
sure, good point about references. thanks

**Comment by j-zimnowoda** [comment]
Read https://github.com/jetstack/kube-oidc-proxy
