### ISSUE TITLE
Improve Authentication Flow for User Registration

### ISSUE THREAD

**Issue by rawc0der** [redkubes/otomi-core#210]
# User story
As a user, I want to be able to login to Keycloak after IDP settings reconfiguration.
The problem we have now is that Keycloak is restarting the registration process after IDP settings updates.
The current configuration for the User Registration process does not allow re-submitting registration or updating existing user entry using the Browser flow.

# Tasks

core:
- [ ] Investigate alternative Authentication Flow methods
- [ ] Implement the custom user registration flow

tasks:
- [ ] Update source code to reflect new settings

# Definition Of Done
- [ ] Tasks are done
- [ ] (Unit) Tests are performed
- [ ] (Architecture) Design Record(s) have been added as `adr/*.md` and appended to list in `adr/_index.md`
- [ ] Specs and demo files have been updated to reflect code changes
- [ ] Documentation has been updated
- [ ] Functionality, code, and/or documentation has been peer reviewed
- [ ] Relevant team members have been notified

**Comment by j-zimnowoda** [comment]
@rawc0der is it still valid ?

**Comment by rawc0der** [comment]
Somehow I was still able to reproduce the issue on my local, regardless of the previous "update" we did. We can keep this open imo.

**Comment by rawc0der** [comment]
The current spec is probably broke for some Admin REST api calls, although the part of the API for `AuthenticationFlowManagement` is working. Currently I did not manage to extract all proper calls to create an AuthenticationFlow from scratch.

Closing this issue as I did not make a lot of progress without an officially provided openAPI spec / official npm package or examples.
