### ISSUE TITLE
As a user of Otomi CE, I want to have an abstraction for k8s ConfigMaps Secrets, so I can mount it in my job

### ISSUE THREAD

**Issue by svatwork** [redkubes/otomi-core#286]
# Story
This is a split story from #204.

The vision is that we offer abstractions that deal with what is published via otomi only. We will allow the mounting of configmaps and secrets only, so we have to offer abstractions for that. Suggestion for an end-result in `otomi-values`:
```
mounts:
  - type: config|secret
    # name is transformed into volumeName later:
    name: name-of-some-config-or-generic-secret
    entries: 
      - key: some-key-in-configmap-or-secret
        path: /some/path
        subPath: some-sub-path
```

Suggestion for `values-schema.yaml`:
```
mounts:
    items:
      properties:
        entries:
          items:
            properties:
              key:
                default: my-key
                type: string
              path:
                default: /path/to/value
                type: string
              subPath:
                default: /optional/subpath
                type: string
            type: array
        name:
          default: my-new-mount
          pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
          type: string
        type:
          default: config
          enum:
            - config
            - secret
          type: string
    type: array
```
# Tasks

core:
1. [ ] Propose values-schema modification based on "suggestion in `otomi-values`". 
2. [ ] Modify `otomi-core/charts/jobs/*.yaml` by looping over all mounts and inner looping all entries. Read out all keys and mount them in `otomi-core/charts/jobs/configmap.yaml` and `otomi-core/charts/jobs/secret.yaml`

# Definition Of Done
- [ ] Tasks are done
- [ ] (Unit) Tests are added to code
- [ ] (Architecture) Design Record(s) have been added as `adr/*.md` and appended to list in `adr/_index.md`
- [ ] Specs and demo files have been updated to reflect code changes
- [ ] Documentation has been updated
- [ ] Functionality, code, and/or documentation has been peer reviewed
- [ ] Relevant team members have been notified

**Comment by Morriz** [comment]
Why is this split off? It is part of the solution. Please stop doing this if you can just solve it in your open PR.
