### ISSUE TITLE
As a user of Otomi CE, I want a change in my k8s ConfigMap and Secret detected automatically, so I can spend less time on managing team jobs

### ISSUE THREAD

**Issue by svatwork** [redkubes/otomi-core#287]
# User story
This story is split from #204.

The relevant chart is `otomi-core/chart/jobs`.

# Tasks

core:
1. [ ] Propose `values-schema.yaml` modification (if necessary)
2. [ ] Refactor out the boolean logic and replace it with the computation of a hash function which will detect whether a k8s ConfigMap or Secret has been modified. 
3. [ ] Add the runPolicy key as an annotation in the job spec.
4. [ ] Remove the logic for `cronJob`, because it has no meaning there.

api:
1. [ ] Look at the example here so you don't need to reinvent the wheel.

# Definition Of Done
- [ ] Tasks are done
- [ ] (Unit) Tests are added to code
- [ ] (Architecture) Design Record(s) have been added as `adr/*.md` and appended to list in `adr/_index.md`
- [ ] Specs and demo files have been updated to reflect code changes
- [ ] Documentation has been updated
- [ ] Functionality, code, and/or documentation has been peer reviewed
- [ ] Relevant team members have been notified

**Comment by Morriz** [comment]
same...close and integrate in your open PR
