### ISSUE TITLE
Install otomi from a chart

### ISSUE THREAD

**Issue by Morriz** [redkubes/otomi-core#374]
# User story
As a user, I want to install otomi on a cluster with a helm chart, so I can access the console immediately.

This makes it easier for others to install otomi.

## Use cases

1. A user can install otomi from a remote chart (providing a pull secret)
2. A user can start a proxy to the console

## Definition Of Ready

- [ ] Requirements have been reviewed, agreed and locked in discussion: 
- [ ] The story is self-contained and has no dependencies
- [ ] The story is reviewed and approved by the stake holders
- [ ] The story has been estimated in complexity points
- [ ] The story use cases are clear and can be translated into test scenarios
- [ ] Atomic SMART tasks have been created that reflect the functional requirements from the discussion
- [ ] SMART tasks reflect any dependencies on other tasks in this story (affecting order of delivery)

## Tasks

core:
1. [ ] Create `charts/install` that holds `templates/job.yaml` to run `bin/install.sh` script that installs: gitea, api and console and shows the isntructions to access it afterwards:
- start proxy command: `kubectl -n shared port-forward svc/otomi-console 8080:80`
- show url to acces the proxied service: `http://127.0.0.1:8080`

## Definition Of Done

- [ ] [Tasks](##Tasks) are done.
- [ ] (Unit) Tests are added with the code (if relevant and practical)
- [ ] (Architecture) Design Record(s) have been added as `adr/*.md` and appended to list in `adr/_index.md`.
- [ ] Schema and demo files have been updated to reflect code changes (if relevant).
- [ ] Documentation has been updated (if relevant).
- [ ] Functionality, code, and/or documentation have been peer reviewed.

**Comment by j-zimnowoda** [comment]
So weird. It was closed automatically after I merged https://github.com/redkubes/otomi-core/pull/382

**Comment by Morriz** [comment]
I must have pasted the wrong hash in the pr description :|
