### ISSUE TITLE
A user can set default response headers for its team services

### ISSUE THREAD

**Issue by bartusz01** [redkubes/otomi-core#789]
# User story
A user can set default response headers for its team services, so developers do not need to modify application code.

Original issue link: https://app.zenhub.com/workspaces/dev-5e7e84dddc966f05a627a19b/issues/redkubes/otomi-core/789
## Use cases
A user can enable predefined [OWASP secure headers](https://owasp.org/www-project-secure-headers/#div-headers) for HTTP response 
```
X-Frame-Options: sameorigin
# This will force service devs to set the correct mime types, so might be impactful:
X-Content-Type-Options: nosniff
Referrer-Policy: no-referrer
Cross-Origin-Embedder-Policy: require-corp
Cross-Origin-Opener-Policy: same-origin
Cross-Origin-Resource-Policy: same-origin
Cache-Control: no-store, max-age=0
Pragma: no-cache
```
A user can tune [OWASP secure headers](https://owasp.org/www-project-secure-headers/#div-headers) parameters

## Definition Of Ready

- [ ] The story use cases are clear and described in Gherkin
- [ ] Requirements and use cases have been reviewed (in our daily session -- the developers rotate -- everyone is responsible!)
- [ ] The story is self-contained and has no dependencies on other stories
- [ ] The story has been estimated in complexity points
- [ ] Atomic SMART tasks have been created that reflect the functional requirements
- [ ] Atomic SMART tasks reflect any dependencies on other tasks in this story (affecting order of delivery)
- [ ] The story is reviewed and approved by @srodenhuis or @morriz

## Tasks

core:
1. [ ] define schema for response headers, so a user can specify its input in values repo
1. [ ] modify VirtualService of team services  (charts/team-ns/), so Istio adds repose headers (https://istiobyexample.dev/response-headers/)

api:
1. [ ] define schema for response headers (src/openapi/service.yaml), so input form is rendered at otomi-console

console: 
1. [ ] rebuild model `gen:store`

## Definition Of Done

- [ ] [Tasks](##Tasks) are done.
- [ ] Unit Tests are added with the code (if relevant and practical)
- [ ] Functional Tests are written down (if relevant and practical)
- [ ] Functional Tests are performed by another developer/ tester(if relevant and practical)
- [ ] (Architecture) Design Record(s) have been added as `adr/*.md` and appended to list in `adr/_index.md`.
- [ ] Schema and demo files have been updated to reflect code changes (if relevant).
- [ ] Documentation has been updated (if relevant).
- [ ] Functionality, code, and/or documentation have been peer reviewed.

**Comment by j-zimnowoda** [comment]
That is a very cool feature.

**Comment by Morriz** [comment]
@bartusz01 but coming back to the original use case: OWASP response headers. I think those should always be set as they do no harm or impact perf. So I will rephrase this title to "Set OWASP response headers" for now, so this can continue as is. I think we should just add these to nginx config:
```yaml
controller:
  addHeaders:
    Strict-Transport-Security: max-age=604800; includeSubDomains
    # Any other general headers that need to go here?
```
I also think that we should not expose `/metrics` by sending 401:
```yaml
annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      location /metrics {
        return 401;
      }
```

**Comment by Morriz** [comment]
I do think that certain headers must be configurable per service as those can't be set for all:
```
Content-Security-Policy
X-Permitted-Cross-Domain-Policies
Referrer-Policy
```
Enough options exist to warrant adding headers to a service. I do think that we should configure services by default with a set of sane constructed headers, so that users may override them and add new ones.

**Comment by j-zimnowoda** [comment]
@Morriz, thanks for thorough analysis. I think the functional requirements are already here. Shall we convert it to user story and define tasks?

**Comment by Morriz** [comment]
Good idea

**Comment by j-zimnowoda** [comment]
Closing in favour of https://app.zenhub.com/workspaces/dev-5e7e84dddc966f05a627a19b/issues/redkubes/unassigned-issues/434
