### ISSUE TITLE
Support Kubernetes version 1.24

### ISSUE THREAD

**Issue by srodenhuis** [redkubes/otomi-core#939]
As an admin, I would like to install Otomi on a Kubernetes cluster with version 1.24

## Use cases
1. A user can install Otomi on a K8s 1.24 cluster

## Definition Of Ready
- [ ] The story use cases are clear and described in Gherkin
- [ ] Requirements and use cases have been reviewed (in our daily session -- the developers rotate -- everyone is responsible!)
- [ ] The story is self-contained and has no dependencies on other stories
- [ ] The story has been estimated in complexity points
- [ ] Atomic SMART tasks have been created that reflect the functional requirements
- [ ] Atomic SMART tasks reflect any dependencies on other tasks in this story (affecting order of delivery)
- [ ] The story is reviewed and approved by @srodenhuis or @morriz

## Tasks
core:
1. [ ] This is an incomplete task.
api:
1. [ ] This is an incomplete task.

## Definition Of Done
- [ ] [Tasks](##Tasks) are done.
- [ ] Unit Tests are added with the code (if relevant and practical)
- [ ] Functional Tests are written down (if relevant and practical)
- [ ] Functional Tests are performed by another developer/ tester(if relevant and practical)
- [ ] (Architecture) Design Record(s) have been added as `adr/*.md` and appended to list in `adr/_index.md`.
- [ ] Schema and demo files have been updated to reflect code changes (if relevant).
- [ ] Documentation has been updated (if relevant).
- [ ] Functionality, code, and/or documentation have been peer-reviewed.
